title: "knutzoch.org"
subtitle: "Website of Knut Zoch, Ph.D."
description: "Experimental particle physicist at CERN | ATLAS | Top-quark physics, machine learning, and new physics searches"

url: "https://knutzoch.org"
repository: "knutzk/knutzk.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

locale: "en-US"
timezone: "Europe/Zurich"

author:
  name: "Knut Zoch, Ph.D."
  avatar: "/assets/images/avatar.jpg"
  bio: "Postdoctoral Fellow in Experimental Particle Physics at Harvard University"
  links:
    - label: "Harvard University"
      icon: "fas fa-fw fa-building"
      url: "https://harvard.edu/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=MJ0Q724AAAAJ&hl=en"
    - label: "InspireHEP"
      icon: "fas fa-fw fa-book"
      url: "https://inspirehep.net/authors/1508982"
    - label: "ORCID ID"
      icon: "fas fa-fw fa-id-card"
      url: "https://orcid.org/0000-0003-2138-6187"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/knutzk"

collections:
  publications:
    output: false
    sort_by: date
  posts:
    output: true
    permalink: /blog/:title/
    sort_by: date

include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      read_time: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

breadcrumbs: true
markdown: kramdown
highlighter: rouge
